let number = 6;
if (number % 2 == 0) {
    console.log("Number is even")
}
else { console.log("Number is odd") }


// let score = 35;

// if (score >= 90) {
//     { }
//     console.log("Grade A")
// }
// else if (score >= 80) {
//     console.log("grade B")
// }
// else if (score >= 70) { console.log("grade c") }
// else if (score >= 60) { console.log("gradeD") }

// }else {
//     console.log("fail")
// }
// }

// Voter allowed or not 

let age = 20;

if (age > 18) {
    console.log("Allowed , For Vote")
} else { console.log("Not aalwed for vote ") }